/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hrm;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.mycompany.model.EmployeeFunctionality;
import com.mycompany.model.Employee;
import java.awt.Image;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableRowSorter;
import java.util.regex.Pattern;

        
/**
 *
 * @author shubhamjain
 */
public class EmployeeManagementPortal extends javax.swing.JFrame {

    
    EmployeeFunctionality add_emp;
    private TableRowSorter<DefaultTableModel> sorter;
    
    //regex for employee name
    private static final String name_regex ="^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$";
    private static final Pattern name_pattern = Pattern.compile(name_regex);
        
    //regex for employee email
    private static final String email_regex =
            "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*" +
            "@" + "(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
    private static final Pattern email_pattern = Pattern.compile(email_regex);
    
    
    // regex for india/us phone number with or without dashes
    private static final String phone_regex =
            "^\\D?(\\d{3})\\D?\\D?(\\d{3})\\D?(\\d{4})$";
    private static final Pattern phone_pattern = Pattern.compile(phone_regex);

    public EmployeeManagementPortal() {
                initComponents();
                add_emp= new EmployeeFunctionality();

                 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        addPage = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        AddName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        AddEmployeeID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        AddAge = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        AddPositionTitle = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        AddStartDate = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        AddTeamInfo = new javax.swing.JTextField();
        AddGender = new javax.swing.JComboBox<>();
        AddLevel = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        AddPhoneNumber = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        AddEmailAddress = new javax.swing.JTextField();
        AddBTN = new javax.swing.JButton();
        AddCancelBTN = new javax.swing.JButton();
        test = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        AddPhoto = new java.awt.Button();
        deletePage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        DeleteEmployeeID = new javax.swing.JTextField();
        DeleteBTN = new javax.swing.JButton();
        DeleteCancelBTN = new javax.swing.JButton();
        searchPage = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SearchField = new javax.swing.JTextField();
        SearchBTN = new javax.swing.JButton();
        SearchCancelBTN = new javax.swing.JButton();
        editPage = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        EditCancelBTN = new javax.swing.JButton();
        EditBTN = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        EditPhoneNumber = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        EditStartDate = new javax.swing.JTextField();
        EditPositionTitle = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        EditEmailAddress = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        EditGender = new javax.swing.JComboBox<>();
        jLabel47 = new javax.swing.JLabel();
        EditTeamInfo = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        EditAge = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        EditLevel = new javax.swing.JComboBox<>();
        jLabel50 = new javax.swing.JLabel();
        EditName = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        EditEmployeeID = new javax.swing.JTextField();
        tablePage = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EmployeeDatabase = new javax.swing.JTable();
        viewPage = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        ViewName = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        ViewEmployeeID = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        ViewAge = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        ViewLevel = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        ViewGender = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        ViewTeamInfo = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        ViewEmailAddress = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        ViewPositionTitle = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        ViewPhoneNumber = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        ViewStartDate = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        ViewProfilePhoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setText("Human Resource Management");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel5.setText("Register Employees");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel7.setText("Name");

        AddName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNameActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel8.setText("Employee ID");

        AddEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmployeeIDActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel9.setText("Gender");

        AddAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAgeActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel10.setText("Age");

        AddPositionTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPositionTitleActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel11.setText("Position Title");

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel12.setText("Level");

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel13.setText("Start date");

        AddStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStartDateActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel14.setText("Team Info");

        AddTeamInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTeamInfoActionPerformed(evt);
            }
        });

        AddGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select gender", "Male", "Female" }));
        AddGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddGenderActionPerformed(evt);
            }
        });

        AddLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Level", "Level 1", "Level 2", "Level 3", " " }));
        AddLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddLevelActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel15.setText("Email Address");

        AddPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPhoneNumberActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel16.setText("Phone number");

        AddEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmailAddressActionPerformed(evt);
            }
        });

        AddBTN.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        AddBTN.setText("Add");
        AddBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBTNActionPerformed(evt);
            }
        });

        AddCancelBTN.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        AddCancelBTN.setText("Cancel");
        AddCancelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCancelBTNActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel20.setText("Photo");

        AddPhoto.setLabel("Upload Photo");
        AddPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPhotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPageLayout = new javax.swing.GroupLayout(addPage);
        addPage.setLayout(addPageLayout);
        addPageLayout.setHorizontalGroup(
            addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPageLayout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(addPageLayout.createSequentialGroup()
                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPageLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPageLayout.createSequentialGroup()
                        .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addPageLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(AddBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(test, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddCancelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPageLayout.createSequentialGroup()
                                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(addPageLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel5))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addPageLayout.createSequentialGroup()
                                        .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AddGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(AddAge, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(AddPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                                .addComponent(AddEmailAddress)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addPageLayout.createSequentialGroup()
                                        .addComponent(AddName, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                        .addComponent(jLabel8)))
                                .addGap(18, 18, 18)
                                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AddLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(367, Short.MAX_VALUE))
                    .addGroup(addPageLayout.createSequentialGroup()
                        .addComponent(AddPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(815, Short.MAX_VALUE))))
        );
        addPageLayout.setVerticalGroup(
            addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(41, 41, 41)
                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(AddName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(AddEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(AddAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(AddTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(AddGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(AddPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel13)
                    .addComponent(AddStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AddPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPageLayout.createSequentialGroup()
                        .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddCancelBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPageLayout.createSequentialGroup()
                        .addComponent(test, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))))
        );

        jTabbedPane1.addTab("Register", addPage);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Human Resource Management");

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel17.setText("Delete Employees");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel18.setText("Enter the Employee ID to Delete");

        DeleteBTN.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        DeleteBTN.setText("Delete");
        DeleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBTNActionPerformed(evt);
            }
        });

        DeleteCancelBTN.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        DeleteCancelBTN.setText("Cancel");
        DeleteCancelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteCancelBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deletePageLayout = new javax.swing.GroupLayout(deletePage);
        deletePage.setLayout(deletePageLayout);
        deletePageLayout.setHorizontalGroup(
            deletePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletePageLayout.createSequentialGroup()
                .addGroup(deletePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deletePageLayout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(DeleteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183)
                        .addComponent(DeleteCancelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(deletePageLayout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jLabel1))
                    .addGroup(deletePageLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addGroup(deletePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addComponent(DeleteEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(386, Short.MAX_VALUE))
        );
        deletePageLayout.setVerticalGroup(
            deletePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deletePageLayout.createSequentialGroup()
                .addGroup(deletePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(deletePageLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(deletePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeleteCancelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(deletePageLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addGap(99, 99, 99)
                        .addGroup(deletePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeleteEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(0, 213, Short.MAX_VALUE)))
                .addGap(82, 82, 82))
        );

        jTabbedPane1.addTab("Delete", deletePage);

        jLabel3.setText("Search an Employee by their ID, Name, or any other information!");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel6.setText("Human Resource Management");

        SearchBTN.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        SearchBTN.setText("Search");
        SearchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBTNActionPerformed(evt);
            }
        });

        SearchCancelBTN.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        SearchCancelBTN.setText("Cancel");
        SearchCancelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCancelBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPageLayout = new javax.swing.GroupLayout(searchPage);
        searchPage.setLayout(searchPageLayout);
        searchPageLayout.setHorizontalGroup(
            searchPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPageLayout.createSequentialGroup()
                .addGroup(searchPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPageLayout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(jLabel6))
                    .addGroup(searchPageLayout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addGroup(searchPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchPageLayout.createSequentialGroup()
                                .addComponent(SearchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(193, 193, 193)
                                .addComponent(SearchCancelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(searchPageLayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel3)))
                .addContainerGap(356, Short.MAX_VALUE))
        );
        searchPageLayout.setVerticalGroup(
            searchPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPageLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addGroup(searchPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchCancelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103))
        );

        jTabbedPane1.addTab("Search", searchPage);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setText("Human Resource Management");

        jLabel19.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel19.setText("Edit Employees");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        EditCancelBTN.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        EditCancelBTN.setText("Cancel");
        EditCancelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditCancelBTNActionPerformed(evt);
            }
        });

        EditBTN.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        EditBTN.setText("Edit");
        EditBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBTNActionPerformed(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel42.setText("Phone number");

        EditPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPhoneNumberActionPerformed(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel43.setText("Start date");

        EditStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditStartDateActionPerformed(evt);
            }
        });

        EditPositionTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPositionTitleActionPerformed(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel44.setText("Position Title");

        EditEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditEmailAddressActionPerformed(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel45.setText("Email Address");

        jLabel46.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel46.setText("Gender");

        EditGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select gender", "Male", "Female" }));
        EditGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditGenderActionPerformed(evt);
            }
        });

        jLabel47.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel47.setText("Team Info");

        EditTeamInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditTeamInfoActionPerformed(evt);
            }
        });

        jLabel48.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel48.setText("Age");

        EditAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditAgeActionPerformed(evt);
            }
        });

        jLabel49.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel49.setText("Level");

        EditLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Level", "Level 1", "Level 2", "Level 3" }));
        EditLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditLevelActionPerformed(evt);
            }
        });

        jLabel50.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel50.setText("Name");

        EditName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditNameActionPerformed(evt);
            }
        });

        jLabel51.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel51.setText("Employee ID");

        javax.swing.GroupLayout editPageLayout = new javax.swing.GroupLayout(editPage);
        editPage.setLayout(editPageLayout);
        editPageLayout.setHorizontalGroup(
            editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPageLayout.createSequentialGroup()
                .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPageLayout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(jLabel2))
                    .addGroup(editPageLayout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(jLabel19))
                    .addGroup(editPageLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(EditAge, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(515, Short.MAX_VALUE))
            .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(editPageLayout.createSequentialGroup()
                    .addGap(105, 105, 105)
                    .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel50)
                        .addComponent(jLabel48)
                        .addComponent(jLabel46)
                        .addComponent(jLabel45)
                        .addComponent(jLabel42))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(editPageLayout.createSequentialGroup()
                            .addComponent(EditName, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(75, 75, 75)
                            .addComponent(jLabel51)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(EditEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(editPageLayout.createSequentialGroup()
                            .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(editPageLayout.createSequentialGroup()
                                    .addComponent(EditGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(208, 208, 208)
                                    .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel47)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPageLayout.createSequentialGroup()
                                            .addComponent(jLabel49)
                                            .addGap(1, 1, 1))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editPageLayout.createSequentialGroup()
                                    .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(EditPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                        .addComponent(EditEmailAddress))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel44, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel43, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(editPageLayout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addComponent(EditLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(editPageLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(EditStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                        .addComponent(EditPositionTitle)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPageLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(EditTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(editPageLayout.createSequentialGroup()
                            .addComponent(EditBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(180, 180, 180)
                            .addComponent(EditCancelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(349, Short.MAX_VALUE)))
        );
        editPageLayout.setVerticalGroup(
            editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPageLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addGap(87, 87, 87)
                .addComponent(EditAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 307, Short.MAX_VALUE))
            .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(editPageLayout.createSequentialGroup()
                    .addGap(107, 107, 107)
                    .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel50)
                        .addComponent(EditName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel51)
                        .addComponent(EditEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel48)
                        .addComponent(EditLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel49))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel47)
                        .addComponent(EditTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel46)
                        .addComponent(EditGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel44)
                        .addComponent(EditPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel45)
                        .addComponent(EditEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(EditStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel43)
                            .addComponent(jLabel42)
                            .addComponent(EditPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                    .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EditBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EditCancelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(48, 48, 48)))
        );

        jTabbedPane1.addTab("Update", editPage);

        EmployeeDatabase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Employee ID", "Age", "Gender", "Phone Number", "Email Address", "Start Date", "Team Info", "Level", "Position", "Photo"
            }
        ));
        EmployeeDatabase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeeDatabaseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(EmployeeDatabase);

        javax.swing.GroupLayout tablePageLayout = new javax.swing.GroupLayout(tablePage);
        tablePage.setLayout(tablePageLayout);
        tablePageLayout.setHorizontalGroup(
            tablePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE)
        );
        tablePageLayout.setVerticalGroup(
            tablePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Database", tablePage);

        viewPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewPageMouseClicked(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel21.setText("Name");

        ViewName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewNameActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel22.setText("Employee ID");

        jLabel23.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel23.setText("Age");

        ViewAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAgeActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel24.setText("Level");

        ViewLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level 1", "Level 2", "Level 3" }));
        ViewLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewLevelActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel25.setText("Gender");

        ViewGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        ViewGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewGenderActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel26.setText("Team Info");

        ViewTeamInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewTeamInfoActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel27.setText("Email Address");

        ViewEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewEmailAddressActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel28.setText("Position Title");

        ViewPositionTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPositionTitleActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel29.setText("Phone Number");

        ViewPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPhoneNumberActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel30.setText("Start date");

        ViewStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewStartDateActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel31.setText("Employee Photo");

        ViewProfilePhoto.setBackground(new java.awt.Color(153, 255, 255));

        javax.swing.GroupLayout viewPageLayout = new javax.swing.GroupLayout(viewPage);
        viewPage.setLayout(viewPageLayout);
        viewPageLayout.setHorizontalGroup(
            viewPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPageLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(viewPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25)
                    .addComponent(jLabel27)
                    .addComponent(jLabel29))
                .addGroup(viewPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewPageLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(viewPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewPageLayout.createSequentialGroup()
                                .addGroup(viewPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ViewGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ViewAge, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(viewPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(ViewPhoneNumber)
                                        .addComponent(ViewEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(viewPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(viewPageLayout.createSequentialGroup()
                                .addComponent(ViewName, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                                .addComponent(jLabel22)))
                        .addGap(18, 18, 18)
                        .addGroup(viewPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ViewLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(281, 281, 281))
                    .addGroup(viewPageLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ViewProfilePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        viewPageLayout.setVerticalGroup(
            viewPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPageLayout.createSequentialGroup()
                .addGroup(viewPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewPageLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel31)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewPageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ViewProfilePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(viewPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(ViewName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(ViewEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(ViewAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(ViewTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(ViewGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(ViewPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(ViewStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inspect Profile", viewPage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchCancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCancelBTNActionPerformed
        SearchField.setText("");

        DefaultTableModel model = (DefaultTableModel) EmployeeDatabase.getModel();
        sorter = new TableRowSorter<>(model);
        EmployeeDatabase.setRowSorter(sorter);
        sorter.setRowFilter(null);
        jTabbedPane1.setSelectedIndex(4);

        // TODO add your handling code here:
    }//GEN-LAST:event_SearchCancelBTNActionPerformed

    private void SearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBTNActionPerformed
        DefaultTableModel model = (DefaultTableModel) EmployeeDatabase.getModel();
        sorter = new TableRowSorter<>(model);
        EmployeeDatabase.setRowSorter(sorter);
        String searchText= SearchField.getText();
        if(searchText.length()==0){
            sorter.setRowFilter(null);
        }
        else{
            sorter.setRowFilter(RowFilter.regexFilter(searchText));
            jTabbedPane1.setSelectedIndex(4);

        }

//        String searchText= searchField.getText();
//        for(Employee emp: add_emp.getEmployee_list() ){
//            if(searchText.equalsIgnoreCase(emp.getEmployeeID()) || searchText.equalsIgnoreCase(emp.getName()) || searchText.equalsIgnoreCase(emp.getEmailID() )){
//               add_emp.getEmployee_list();
//                System.out.println("searched successfully");
//                employeeTable();
//                break;                
//            }
//        }

        

        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBTNActionPerformed

    private void EmployeeDatabaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeDatabaseMouseClicked
        int selected = EmployeeDatabase.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) EmployeeDatabase.getModel();
        
        
        //code for the edit screen
        EditName.setText(model.getValueAt(selected,0).toString());
        EditEmployeeID.setText(model.getValueAt(selected,1).toString());
        EditAge.setText(model.getValueAt(selected,2).toString());
        String emp_gender = model.getValueAt(selected, 3).toString();
        switch(emp_gender){
            case "Male": {
                EditGender.setSelectedIndex(1);
                break;
            }
            case "Female": {
                EditGender.setSelectedIndex(2);
                break;

            }

        }
        EditStartDate.setText(model.getValueAt(selected,4).toString());
        EditTeamInfo.setText(model.getValueAt(selected,5).toString());
        String emp_level = model.getValueAt(selected, 6).toString();
        switch(emp_level){
            case "Level 1": {
                EditLevel.setSelectedIndex(1);
                break;
            }
            case "Level 2": {
                EditLevel.setSelectedIndex(2);
                break;

            }

            case "Level 3": {
                EditLevel.setSelectedIndex(3);
                break;

            }
          

        }

        EditPositionTitle.setText(model.getValueAt(selected,7).toString());
        EditPhoneNumber.setText(model.getValueAt(selected,8).toString());
        EditEmailAddress.setText(model.getValueAt(selected,9).toString());
        
 
        
        
        
        
        //code for the viewscreen
        
        ViewName.setText(model.getValueAt(selected,0).toString());
        ViewEmployeeID.setText(model.getValueAt(selected,1).toString());
        ViewAge.setText(model.getValueAt(selected,2).toString());
        String view_emp_gender = model.getValueAt(selected, 3).toString();
        switch(view_emp_gender){
            case "Male": {
                ViewGender.setSelectedIndex(1);
                break;
            }
            case "Female": {
                ViewGender.setSelectedIndex(2);
                break;

            }

        }
        ViewStartDate.setText(model.getValueAt(selected,4).toString());
        ViewTeamInfo.setText(model.getValueAt(selected,5).toString());
        String view_emp_level = model.getValueAt(selected, 6).toString();
        switch(view_emp_level){
            case "Level 1": {
                ViewLevel.setSelectedIndex(1);
                break;
            }
            case "Level 2": {
                ViewLevel.setSelectedIndex(2);
                break;

            }

            case "Level 3": {
                ViewLevel.setSelectedIndex(3);
                break;

            }
           

        }

        ViewPositionTitle.setText(model.getValueAt(selected,7).toString());
        ViewPhoneNumber.setText(model.getValueAt(selected,8).toString());
        ViewEmailAddress.setText(model.getValueAt(selected,9).toString());
        ImageIcon i = new ImageIcon(model.getValueAt(selected,10).toString());
        Image image = i.getImage().getScaledInstance(ViewProfilePhoto.getWidth(), ViewProfilePhoto.getHeight(), Image.SCALE_SMOOTH);
        ViewProfilePhoto.setIcon(new ImageIcon(image));
        ViewName.setEnabled(false);
        ViewEmployeeID.setEnabled(false);
        ViewAge.setEnabled(false);
        ViewGender.setEnabled(false);
        ViewStartDate.setEnabled(false);
        ViewTeamInfo.setEnabled(false);
        ViewLevel.setEnabled(false);
        ViewPositionTitle.setEnabled(false);
        ViewPhoneNumber.setEnabled(false);
        ViewEmailAddress.setEnabled(false);

        

        
        
        
        
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeDatabaseMouseClicked

    private void AddPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPhotoActionPerformed
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images","jpg","png","jpeg");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if(result==JFileChooser.APPROVE_OPTION){
            File selected = file.getSelectedFile();
            String path = selected.getAbsolutePath();
            add_emp.setImgPath(path);
            JOptionPane.showMessageDialog(null,"Profile photo added successfully");

            
//            ImageIcon i = new ImageIcon(path);
//            Image image = i.getImage().getScaledInstance(viewProfilePhoto1.getWidth(), viewProfilePhoto1.getHeight(), Image.SCALE_SMOOTH);
//            viewProfilePhoto1.setIcon(new ImageIcon(image));

        }
        else if(result == JFileChooser.CANCEL_OPTION){
            System.out.println("No File Selected");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_AddPhotoActionPerformed

    private void AddCancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCancelBTNActionPerformed
        AddName.setText("");
        AddEmployeeID.setText("");
        AddAge.setText("");
        AddGender.setSelectedIndex(0);
        AddStartDate.setText("");
        AddTeamInfo.setText("");
        AddLevel.setSelectedIndex(0);
        AddPositionTitle.setText("");
        AddPhoneNumber.setText("");
        AddEmailAddress.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_AddCancelBTNActionPerformed

    
    
    
    private void AddBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBTNActionPerformed
        
        try {
            
            String name = AddName.getText();
            String employeeID = AddEmployeeID.getText();
            String age = AddAge.getText();
            int EmpAge = 0;
            EmpAge = Integer.parseInt(age);
            String gender = AddGender.getSelectedItem().toString();
            String startDate = AddStartDate.getText();

            SimpleDateFormat date_formatter = new SimpleDateFormat("MM/dd/yyyy");
            Date date = new Date();
            date = date_formatter.parse(startDate);
            String level = AddLevel.getSelectedItem().toString();
            String teamInfo = AddTeamInfo.getText();
            String position = AddPositionTitle.getText();
            String phone = AddPhoneNumber.getText();
            String emailID = AddEmailAddress.getText();

            String photo = add_emp.getImgPath();

            if (age != null && !age.isEmpty() && name != null && !name.isEmpty() && employeeID != null && !employeeID.isEmpty() && gender != null && !gender.isEmpty() && level != null && !level.isEmpty() && teamInfo != null && !teamInfo.isEmpty() && position != null && !position.isEmpty() && phone != null && !phone.isEmpty() && emailID != null && !emailID.isEmpty() && photo != null && !photo.isEmpty() && name_pattern.matcher(name).matches() && phone_pattern.matcher(phone).matches() && email_pattern.matcher(emailID).matches()) {
                JOptionPane.showMessageDialog(AddBTN, "Employee data is successfully added");
                Employee emp = add_emp.addNewEmployee();
                emp.setName(name);
                emp.setEmployeeID(employeeID);
                emp.setAge(EmpAge);
                emp.setGender(gender);
                emp.setStartDate(date);
                emp.setLevel(level);
                emp.setTeamInfo(teamInfo);
                emp.setPosition(position);
                emp.setPhone(phone);
                emp.setEmailID(emailID);
                emp.setImage(photo);
                employeeTable();
                jTabbedPane1.setSelectedIndex(4);

                AddName.setText("");
                AddEmployeeID.setText("");
                AddAge.setText("");
                AddGender.setSelectedIndex(0);
                AddStartDate.setText("");
                AddTeamInfo.setText("");
                AddLevel.setSelectedIndex(0);
                AddPositionTitle.setText("");
                AddPhoneNumber.setText("");
                AddEmailAddress.setText("");
            } else {
                JOptionPane.showMessageDialog(AddBTN, "Please check the fields!!");

            }
        }
        
        catch (Exception e) {
            JOptionPane.showMessageDialog(AddBTN, "Please check all the Fields!");
        }

        

        //    String photo;                   // TODO add your handling code here:
    }//GEN-LAST:event_AddBTNActionPerformed

    private void AddEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddEmailAddressActionPerformed

    private void AddPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddPhoneNumberActionPerformed

    private void AddLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddLevelActionPerformed

    private void AddGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddGenderActionPerformed

    private void AddTeamInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTeamInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddTeamInfoActionPerformed

    private void AddStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddStartDateActionPerformed

    private void AddPositionTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPositionTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddPositionTitleActionPerformed

    private void AddAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddAgeActionPerformed

    private void AddNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddNameActionPerformed

    private void DeleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBTNActionPerformed

        String deleteEmployeeID = DeleteEmployeeID.getText();

        Employee temp = null;

        for(Employee emp: add_emp.getEmployee_list()) {
            if(emp.getEmployeeID().equals(deleteEmployeeID)) {
                temp = emp;

            }
           
        }
        add_emp.getEmployee_list().remove(temp);
        JOptionPane.showMessageDialog(DeleteBTN,"Employee data is successfully deleted");
        jTabbedPane1.setSelectedIndex(4);
        employeeTable();
    }//GEN-LAST:event_DeleteBTNActionPerformed

    private void EditNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditNameActionPerformed

    private void EditLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditLevelActionPerformed

    private void EditAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditAgeActionPerformed

    private void EditTeamInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditTeamInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditTeamInfoActionPerformed

    private void EditGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditGenderActionPerformed

    private void EditEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditEmailAddressActionPerformed

    private void EditPositionTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPositionTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditPositionTitleActionPerformed

    private void EditStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditStartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditStartDateActionPerformed

    private void EditPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditPhoneNumberActionPerformed

    private void EditBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBTNActionPerformed
        int edit = EmployeeDatabase.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) EmployeeDatabase.getModel();
        if(edit>=0){
            model.setValueAt(EditName.getText(), edit, 0);
            model.setValueAt(EditEmployeeID.getText(), edit, 1);
            model.setValueAt(EditAge.getText(), edit, 2);
            model.setValueAt(EditGender.getSelectedItem().toString(), edit, 3);
            model.setValueAt(EditStartDate.getText(), edit, 4);
            model.setValueAt(EditTeamInfo.getText(), edit, 5);
            model.setValueAt(EditLevel.getSelectedItem().toString(), edit, 6);
            model.setValueAt(EditPositionTitle.getText(), edit, 7);
            model.setValueAt(EditPhoneNumber.getText(), edit, 8);
            model.setValueAt(EditEmailAddress.getText(), edit, 9);
            JOptionPane.showMessageDialog(AddBTN,"Employee data is edited successfully");
            jTabbedPane1.setSelectedIndex(4);
            EditName.setText("");
            EditEmployeeID.setText("");
            EditAge.setText("");
            EditGender.setSelectedIndex(0);
            EditStartDate.setText("");
            EditTeamInfo.setText("");
            EditLevel.setSelectedIndex(0);
            EditPositionTitle.setText("");
            EditPhoneNumber.setText("");
            EditEmailAddress.setText("");

        }
        else{
            JOptionPane.showMessageDialog(null,"Please select a row from the table");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_EditBTNActionPerformed

    private void EditCancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditCancelBTNActionPerformed
        // TODO add your handling code here:
        EditName.setText("");
        EditAge.setText("");
        EditGender.setSelectedIndex(0);
        EditStartDate.setText("");
        EditTeamInfo.setText("");
        EditLevel.setSelectedIndex(0);
        EditPositionTitle.setText("");
        EditPhoneNumber.setText("");
        EditEmailAddress.setText("");
    }//GEN-LAST:event_EditCancelBTNActionPerformed

    private void ViewNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewNameActionPerformed

    private void ViewAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewAgeActionPerformed

    private void ViewLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewLevelActionPerformed

    private void ViewGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewGenderActionPerformed

    private void ViewTeamInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewTeamInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewTeamInfoActionPerformed

    private void ViewEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewEmailAddressActionPerformed

    private void ViewPositionTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPositionTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewPositionTitleActionPerformed

    private void ViewPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewPhoneNumberActionPerformed

    private void ViewStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewStartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewStartDateActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void viewPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPageMouseClicked
       
    }//GEN-LAST:event_viewPageMouseClicked

    private void DeleteCancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteCancelBTNActionPerformed
        DeleteEmployeeID.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteCancelBTNActionPerformed

    private void AddEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmployeeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddEmployeeIDActionPerformed

    
    
    //function when user clicks add button
    
    
    //function when user clicks delete button
    
    
    //function when user clicks edit button
    
  //function when user clicks cancel button(Edit)
    
//function when user clicks search button
    
    
//function to populate row-content of table to edit page
    
      //function when user clicks cancel button(Add)

    
 //function when user clicks cancel button(Search)
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagementPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagementPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagementPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagementPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeManagementPortal().setVisible(true);
            }
        });
    }
    
//function to add content to the table    
    private void employeeTable(){
        DefaultTableModel model = (DefaultTableModel) EmployeeDatabase.getModel();
        model.setRowCount(0);
        for(Employee emp: add_emp.getEmployee_list()){
            Object[] row = new Object[13];
            row[0]=emp.getName();
            row[1]=emp.getEmployeeID();
            row[2]=emp.getAge();
            row[3]=emp.getGender();
            SimpleDateFormat date_formatter = new SimpleDateFormat("dd-MM-yyyy");
            row[4]=date_formatter.format(emp.getStartDate());
            row[6]=emp.getLevel();
            row[5]=emp.getTeamInfo();
            row[7]=emp.getPosition();
            row[8]=emp.getPhone();
            row[9]=emp.getEmailID();
            row[10]=emp.getImage();
            System.out.println(row[10]+"this is img");
           model.addRow(row) ;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddAge;
    private javax.swing.JButton AddBTN;
    private javax.swing.JButton AddCancelBTN;
    private javax.swing.JTextField AddEmailAddress;
    private javax.swing.JTextField AddEmployeeID;
    private javax.swing.JComboBox<String> AddGender;
    private javax.swing.JComboBox<String> AddLevel;
    private javax.swing.JTextField AddName;
    private javax.swing.JTextField AddPhoneNumber;
    private java.awt.Button AddPhoto;
    private javax.swing.JTextField AddPositionTitle;
    private javax.swing.JTextField AddStartDate;
    private javax.swing.JTextField AddTeamInfo;
    private javax.swing.JButton DeleteBTN;
    private javax.swing.JButton DeleteCancelBTN;
    private javax.swing.JTextField DeleteEmployeeID;
    private javax.swing.JTextField EditAge;
    private javax.swing.JButton EditBTN;
    private javax.swing.JButton EditCancelBTN;
    private javax.swing.JTextField EditEmailAddress;
    private javax.swing.JTextField EditEmployeeID;
    private javax.swing.JComboBox<String> EditGender;
    private javax.swing.JComboBox<String> EditLevel;
    private javax.swing.JTextField EditName;
    private javax.swing.JTextField EditPhoneNumber;
    private javax.swing.JTextField EditPositionTitle;
    private javax.swing.JTextField EditStartDate;
    private javax.swing.JTextField EditTeamInfo;
    private javax.swing.JTable EmployeeDatabase;
    private javax.swing.JButton SearchBTN;
    private javax.swing.JButton SearchCancelBTN;
    private javax.swing.JTextField SearchField;
    private javax.swing.JTextField ViewAge;
    private javax.swing.JTextField ViewEmailAddress;
    private javax.swing.JTextField ViewEmployeeID;
    private javax.swing.JComboBox<String> ViewGender;
    private javax.swing.JComboBox<String> ViewLevel;
    private javax.swing.JTextField ViewName;
    private javax.swing.JTextField ViewPhoneNumber;
    private javax.swing.JTextField ViewPositionTitle;
    private javax.swing.JLabel ViewProfilePhoto;
    private javax.swing.JTextField ViewStartDate;
    private javax.swing.JTextField ViewTeamInfo;
    private javax.swing.JPanel addPage;
    private javax.swing.JPanel deletePage;
    private javax.swing.JPanel editPage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel searchPage;
    private javax.swing.JPanel tablePage;
    private javax.swing.JLabel test;
    private javax.swing.JPanel viewPage;
    // End of variables declaration//GEN-END:variables
}


